### ISSUE TITLE
issue #1 make search result width equal to the search bar.

### ISSUE THREAD

**Issue by pushsontakke** [pushsontakke/Practices#1]
![image](https://github.com/pushsontakke/Practices/assets/116652189/346a8660-7605-4b7c-8b71-66a95a7e411f)

you can see when search result appear. the width of the results section is not equal to the search bar.

**Comment by Sky-De** [comment]
@pushsontakke assign this to me, i would like to work on this
Thanks

**Comment by pushsontakke** [comment]
@Sky-De you can complete it. Also you can add custom style as you like.
by the way its just a search bar. so you can do as you like.

**Comment by Sky-De** [comment]
@pushsontakke Hi, it's been about three weeks since I requested for assignment. Can you confirm that you'll be available to merge my PR once I fix this issue?

**Comment by pushsontakke** [comment]
I'm the only one who maintains this repository. Also, I've been busy and not able to look, but now I will.

**Comment by pushsontakke** [comment]
As I said in my earlier comment, this is just a search bar. But It is going to be part of my project. So Please take note of that.
